# Generated by Django 4.2.4 on 2023-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_processeddata_flame_processeddata_node_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='flame',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='node_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
