# Generated by Django 4.2.4 on 2023-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_processeddata_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
