# Generated by Django 4.2.5 on 2023-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_processeddata_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='mq2_ppm',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='mq3_ppm',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='mq6_ppm',
        ),
        migrations.AddField(
            model_name='processeddata',
            name='mq2_analog',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processeddata',
            name='mq3_analog',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processeddata',
            name='mq6_analog',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
