# Generated by Django 4.1.7 on 2023-10-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_processeddata_mq2_ppm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='MQ2_ppm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='MQ3_ppm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='MQ6_ppm',
            field=models.IntegerField(),
        ),
    ]
