# Generated by Django 4.1.7 on 2023-10-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_rawdata_mq2_ppm_alter_rawdata_mq3_ppm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='MQ2_ppm',
            new_name='MQ2_Data',
        ),
        migrations.RenameField(
            model_name='rawdata',
            old_name='MQ3_ppm',
            new_name='MQ3_Data',
        ),
        migrations.RenameField(
            model_name='rawdata',
            old_name='MQ6_ppm',
            new_name='MQ6_Data',
        ),
    ]
