# Generated by Django 4.2.5 on 2023-10-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_weight_lbs_rawdata_weight_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
