# Generated by Django 4.2.5 on 2023-10-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_processeddata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
