# Generated by Django 4.2.5 on 2023-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_processeddata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
