# Generated by Django 4.2.5 on 2023-10-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bins',
        ),
    ]
